import test from "node:test";
import assert from "node:assert/strict";
import { ALLERGEN_CODES } from "../core/food-restrictions/taxonomy.ts";
import { normalizeRestrictionContext } from "../core/food-restrictions/normalize.ts";
import * as T from "../core/food-catalog/types.ts";
import { validateEntity, validateFoodCatalog } from "../core/food-catalog/validator.ts";
import { computeCatalogCapability, productionCatalogCapability } from "../core/food-catalog/capability.ts";
import { filterCatalog } from "../core/food-catalog/filter.ts";

const H=`sha256:${"a".repeat(64)}`, S=`sha256:${"b".repeat(64)}`, AS_OF="2026-01-01T00:00:00.000Z";
const source=()=>({schemaVersion:T.SOURCE_SCHEMA_VERSION,sourceId:"source_fixture_alpha",sourceType:"official_government_reference",title:"Synthetic source",publisher:"Synthetic publisher",sourceVersion:"fixture-v1",publishedOn:"2025-01-01",verifiedOn:"2025-06-01",locatorType:"document_reference",locator:"fixture-document",sourceFingerprint:H});
const reviews=()=>[
 {schemaVersion:T.REVIEW_SCHEMA_VERSION,reviewId:"review_fixture_allergy",reviewerId:"reviewer_fixture_allergy",reviewerRole:"allergen_celiac_specialist",reviewStatus:"approved",reviewedAt:"2025-12-01T00:00:00.000Z",profileHash:H,sourceSetHash:S,policyVersion:T.CATALOG_POLICY_VERSION},
 {schemaVersion:T.REVIEW_SCHEMA_VERSION,reviewId:"review_fixture_nutrition",reviewerId:"reviewer_fixture_nutrition",reviewerRole:"nutrition_specialist",reviewStatus:"approved",reviewedAt:"2025-12-02T00:00:00.000Z",profileHash:H,sourceSetHash:S,policyVersion:T.CATALOG_POLICY_VERSION},
];
const entity=(id="food_ru_fixture_alpha",profile="profile_ru_fixture_alpha",order=1)=>({schemaVersion:T.ENTITY_SCHEMA_VERSION,foodId:id,entityVersion:1,entityType:"single_food",displayNameRu:"Тестовый объект",slotCodes:["protein_source"],displayOrder:order,safetyProfileRef:{safetyProfileId:profile,safetyProfileVersion:1},lifecycleStatus:"active",lifecycleReason:null,supersedes:null,supersededBy:null,contentHash:H});
const profile=(id="profile_ru_fixture_alpha",food="food_ru_fixture_alpha")=>({schemaVersion:T.SAFETY_PROFILE_SCHEMA_VERSION,safetyProfileId:id,safetyProfileVersion:1,foodId:food,entityVersion:1,profileHash:H,sourceSetHash:S,policyVersion:T.CATALOG_POLICY_VERSION,allergenAssessments:ALLERGEN_CODES.map(code=>({code,ingredientStatus:"does_not_contain",crossContactStatus:"assessed_no_known_warning"})),glutenRelationship:"not_assessed",celiacStatus:"unsupported",dietaryPatternAssessments:T.SUPPORTED_PATTERNS.map(pattern=>({pattern,status:"compatible"})),labelVerificationStatus:"not_applicable",sources:[source()],reviews:reviews()});
const envelope=(entities=[entity()],profiles=[profile()])=>({schemaVersion:T.CATALOG_SCHEMA_VERSION,marketVersion:"nutrimind.market.ru.v1",taxonomyVersion:"nutrimind.food-allergen.ru.v1",policyVersion:T.CATALOG_POLICY_VERSION,contentVersion:T.CATALOG_CONTENT_VERSION,coverageVersion:T.FUTURE_COVERAGE_VERSION,supportedEntityTypes:["single_food"],catalogSupportedAllergenCodes:[...T.FUTURE_SUPPORTED_ALLERGEN_CODES],catalogSupportedDietaryPatterns:[...T.SUPPORTED_PATTERNS],catalogCeliacSupport:"not_supported",entities,safetyProfiles:profiles});
const context=(allergens=[],celiac="no",pattern="omnivore")=>normalizeRestrictionContext({foodAllergyStatus:allergens.length?"known":"none",foodAllergenCodes:allergens,celiacStatus:celiac,dietaryPattern:pattern});
const clone=x=>structuredClone(x);

test("exact versions, coverage and closed vocabularies",()=>{
 assert.deepEqual([T.CATALOG_SCHEMA_VERSION,T.ENTITY_SCHEMA_VERSION,T.SAFETY_PROFILE_SCHEMA_VERSION,T.SOURCE_SCHEMA_VERSION,T.REVIEW_SCHEMA_VERSION,T.CATALOG_POLICY_VERSION,T.CATALOG_CONTENT_VERSION,T.FUTURE_COVERAGE_VERSION],["nutrimind.food-catalog.schema.v1","nutrimind.food-catalog.entity.v1","nutrimind.food-catalog.safety-profile.v1","nutrimind.food-catalog.source.v1","nutrimind.food-catalog.review.v1","nutrimind.food-catalog.policy.ru.v1","nutrimind.food-catalog.ru.v1.0.0","nutrimind.catalog-coverage.ru.v1"]);
 assert.equal(T.FUTURE_SUPPORTED_ALLERGEN_CODES.length,16); assert.ok(!T.FUTURE_SUPPORTED_ALLERGEN_CODES.includes("oats")); assert.equal(ALLERGEN_CODES.length,17); assert.ok(ALLERGEN_CODES.includes("oats")); assert.equal(T.CATALOG_RULE_IDS.length,25); assert.equal(new Set(T.CATALOG_ERROR_CODES).size,T.CATALOG_ERROR_CODES.length);
});

test("production has no artifact and stays abstract-only",()=>{const r=productionCatalogCapability();assert.equal(r.status,"abstract_only");assert.ok(r.errorCodes.includes("CAPABILITY_CATALOG_UNAVAILABLE"));assert.ok(r.warningCodes.includes("CATALOG_NO_PRODUCTION_CONTENT"));assert.ok(Object.isFrozen(r));});

test("valid catalog is canonical, immutable and input is untouched",()=>{const raw=envelope();const before=JSON.stringify(raw);const r=validateFoodCatalog(raw,AS_OF);assert.equal(r.status,"valid");assert.equal(JSON.stringify(raw),before);assert.notEqual(r.catalog,raw);assert.ok(Object.isFrozen(r.catalog));assert.ok(Object.isFrozen(r.catalog.entities[0]));assert.ok(Object.isFrozen(r.ruleIds));});

test("unordered profile arrays are accepted and canonicalized",()=>{const p=profile();p.allergenAssessments.reverse();p.dietaryPatternAssessments.reverse();p.reviews.reverse();const r=validateFoodCatalog(envelope([entity()],[p]),AS_OF);assert.equal(r.status,"valid");assert.deepEqual(r.catalog.safetyProfiles[0].allergenAssessments.map(x=>x.code),ALLERGEN_CODES);assert.deepEqual(r.catalog.safetyProfiles[0].dietaryPatternAssessments.map(x=>x.pattern),T.SUPPORTED_PATTERNS);assert.equal(r.catalog.safetyProfiles[0].reviews[0].reviewerRole,"allergen_celiac_specialist");});

test("test-only valid empty envelope",()=>{const r=validateFoodCatalog(envelope([],[]),AS_OF);assert.equal(r.status,"valid_empty");assert.deepEqual(r.warningCodes,["CATALOG_EMPTY"]);assert.equal(computeCatalogCapability(context(),r).status,"abstract_only");});

test("strict envelope and exact versions fail closed",()=>{for(const mutate of [x=>x.extra=1,x=>delete x.schemaVersion,x=>x.schemaVersion="future",x=>x.marketVersion="other",x=>x.taxonomyVersion="other",x=>x.policyVersion="other",x=>x.contentVersion="other",x=>x.coverageVersion="other",x=>x.entities={},x=>x.catalogSupportedAllergenCodes=["wheat"]]){const x=envelope();mutate(x);assert.equal(validateFoodCatalog(x,AS_OF).status,"invalid")}});

test("entity identity, slots, lifecycle, versions and hashes are strict",()=>{assert.equal(validateEntity(entity()).status,"valid");for(const mutate of [x=>x.foodId="Food",x=>x.entityVersion=0,x=>x.entityVersion=1.5,x=>x.entityType="sku",x=>x.displayNameRu=" bad ",x=>x.slotCodes=[],x=>x.slotCodes=["protein_source","protein_source"],x=>x.slotCodes=["unknown"],x=>x.contentHash=`sha256:${"A".repeat(64)}`,x=>x.lifecycleStatus="deprecated",x=>x.extra=true]){const x=entity();mutate(x);assert.equal(validateEntity(x).status,"invalid")}});

test("duplicates, orphans and binding mismatches invalidate whole catalog",()=>{const e=entity();assert.equal(validateFoodCatalog(envelope([e,clone(e)],[profile(),profile("profile_ru_fixture_beta","food_ru_fixture_alpha")]),AS_OF).status,"invalid");assert.equal(validateFoodCatalog(envelope([entity()],[]),AS_OF).status,"invalid");const p=profile();p.entityVersion=2;assert.equal(validateFoodCatalog(envelope([entity()],[p]),AS_OF).status,"invalid");});

test("all 17 allergen records are exact and ingredient/cross-contact stay separate",()=>{const p=profile();assert.equal(p.allergenAssessments.length,17);p.allergenAssessments.pop();assert.equal(validateFoodCatalog(envelope([entity()],[p]),AS_OF).status,"invalid");for(const mutate of [a=>a[0].code="unknown",a=>a[1].code=a[0].code,a=>a[0].ingredientStatus="absent",a=>a[0].crossContactStatus="safe",a=>a[0].extra=true]){const q=profile();mutate(q.allergenAssessments);assert.equal(validateFoodCatalog(envelope([entity()],[q]),AS_OF).status,"invalid")}});

test("celiac, gluten, pattern and label metadata are independent and strict",()=>{for(const mutate of [p=>p.glutenRelationship="gluten_free",p=>p.celiacStatus="safe",p=>p.labelVerificationStatus="verified",p=>p.dietaryPatternAssessments.pop(),p=>p.dietaryPatternAssessments[0].status="maybe"]){const p=profile();mutate(p);assert.equal(validateFoodCatalog(envelope([entity()],[p]),AS_OF).status,"invalid")}const conflict=profile();conflict.dietaryPatternAssessments.find(x=>x.pattern==="vegetarian").status="not_compatible";assert.equal(validateFoodCatalog(envelope([entity()],[conflict]),AS_OF).status,"invalid");});

test("source schema, dates, HTTPS and uniqueness are strict",()=>{for(const mutate of [s=>s.sourceType="retailer_listing",s=>s.verifiedOn="2024-01-01",s=>s.verifiedOn="2027-01-01",s=>s.locatorType="https_url",s=>{s.locatorType="https_url";s.locator="http://example.test"},s=>s.sourceFingerprint=`sha256:${"A".repeat(64)}`,s=>s.extra=true]){const p=profile();mutate(p.sources[0]);assert.equal(validateFoodCatalog(envelope([entity()],[p]),AS_OF).status,"invalid")}const p=profile();p.sources.push(clone(p.sources[0]));assert.equal(validateFoodCatalog(envelope([entity()],[p]),AS_OF).status,"invalid");});

test("two independent specialist reviews and bindings are required",()=>{for(const mutate of [p=>p.reviews.pop(),p=>p.reviews[1].reviewerId=p.reviews[0].reviewerId,p=>p.reviews[1].reviewerRole="technical_validator",p=>p.reviews[0].reviewStatus="changes_required",p=>p.reviews[0].profileHash=S,p=>p.reviews[0].sourceSetHash=H,p=>p.reviews[0].policyVersion="future",p=>p.reviews[0].extra=true]){const p=profile();mutate(p);assert.equal(validateFoodCatalog(envelope([entity()],[p]),AS_OF).status,"invalid")}});

test("review expiry is exact and deterministic",()=>{const p=profile();p.reviews[0].reviewedAt="2025-01-01T00:00:00.000Z";p.reviews[1].reviewedAt="2025-01-01T00:00:00.000Z";assert.equal(validateFoodCatalog(envelope([entity()],[p]),"2025-06-29T23:59:59.999Z").status,"valid");assert.equal(validateFoodCatalog(envelope([entity()],[p]),"2025-06-30T00:00:00.000Z").status,"invalid");});

test("capability gates context, celiac, oats and unsupported states",()=>{const c=validateFoodCatalog(envelope(),AS_OF);assert.equal(computeCatalogCapability(context(),c).status,"concrete_available");let r=computeCatalogCapability(context([],"confirmed"),c);assert.deepEqual(r.errorCodes,["CAPABILITY_CELIAC_UNSUPPORTED"]);r=computeCatalogCapability(context(["oats"]),c);assert.deepEqual(r.errorCodes,["CAPABILITY_OATS_UNSUPPORTED"]);assert.equal(computeCatalogCapability({...context(),status:"unresolved"},c).status,"abstract_only");assert.equal(computeCatalogCapability(context(),validateFoodCatalog(null,AS_OF)).status,"abstract_only");});

test("filter uses exact full allergy intersection and pattern/cross-contact gates",()=>{const p=profile();p.allergenAssessments.find(x=>x.code==="milk").ingredientStatus="contains";p.allergenAssessments.find(x=>x.code==="eggs").crossContactStatus="unknown";const c=validateFoodCatalog(envelope([entity()],[p]),AS_OF);assert.equal(c.status,"valid");let ctx=context(["milk","eggs"]);let cap=computeCatalogCapability(ctx,c);let r=filterCatalog(c,cap,ctx,"protein_source");assert.equal(r.status,"empty");assert.deepEqual(r.exclusions[0].errorCodes,["FILTER_ENTITY_EXCLUDED_ALLERGEN","FILTER_ENTITY_EXCLUDED_CROSS_CONTACT"]);ctx=context();cap=computeCatalogCapability(ctx,c);r=filterCatalog(c,cap,ctx,"protein_source");assert.equal(r.status,"matched");assert.equal(filterCatalog(c,cap,ctx,"bad_slot").status,"slot_unsupported");assert.ok(Object.isFrozen(r.items));});

test("filter does not use fuzzy or substring matching and never mutates",()=>{const raw=envelope(),before=JSON.stringify(raw),c=validateFoodCatalog(raw,AS_OF),ctx=context(["fish"]),cap=computeCatalogCapability(ctx,c);filterCatalog(c,cap,ctx,"protein_source");assert.equal(JSON.stringify(raw),before);assert.equal(c.status,"valid");});

test("catalog domain is structurally separated from portions, macros and network state",async()=>{const fs=await import("node:fs/promises");const files=["types.ts","validator.ts","capability.ts","filter.ts"];const text=(await Promise.all(files.map(f=>fs.readFile(new URL(`../core/food-catalog/${f}`,import.meta.url),"utf8")))).join("\n");for(const forbidden of ["window.","document.","sessionStorage","localStorage","indexedDB","fetch(","analytics","servingSize","portionGrams","macroTarget","OpenAI"]){assert.equal(text.includes(forbidden),false,forbidden)}});
