import assert from "node:assert/strict";
import test from "node:test";
import { runPhase3A, normalizeCurrentMealPattern } from "../core/calculation/index.ts";
import { runQuestionnairePipeline } from "../core/questionnaire-adapter.ts";
import { normalizeRestrictionContext } from "../core/food-restrictions/normalize.ts";
import { validateGenericFoodCatalog } from "../core/generic-food-catalog/validator.ts";
import { computeGenericExampleCapability } from "../core/generic-food-catalog/capability.ts";
import { filterGenericFoodCatalog } from "../core/generic-food-catalog/filter.ts";
import * as T from "../core/generic-food-catalog/types.ts";

const H=`sha256:${"a".repeat(64)}`, S=`sha256:${"b".repeat(64)}`, now="2026-08-04T00:00:00.000Z";
const source={schemaVersion:T.GENERIC_SOURCE_SCHEMA_VERSION,sourceId:"generic_source_identity",sourceType:"official_food_definition",sourcePurpose:"generic_identity",title:"Official definition",publisher:"Authority",sourceVersion:"1",publishedOn:"2026-01-01",verifiedOn:"2026-02-01",locatorType:"https_url",locator:"https://example.org/definition",sourceFingerprint:H};
const review=(role,id)=>({schemaVersion:T.GENERIC_REVIEW_SCHEMA_VERSION,reviewId:`generic_review_${id}`,reviewerId:`generic_reviewer_${id}`,reviewerRole:role,reviewStatus:"approved",reviewedAt:"2026-07-01T00:00:00.000Z",profileHash:H,sourceSetHash:S,policyVersion:T.GENERIC_POLICY_VERSION});
const profile={schemaVersion:T.GENERIC_PROFILE_SCHEMA_VERSION,intrinsicProfileId:"generic_profile_ru_fixture_item",intrinsicProfileVersion:1,foodId:"generic_food_ru_fixture_item",entityVersion:1,profileHash:H,sourceSetHash:S,policyVersion:T.GENERIC_POLICY_VERSION,genericIdentity:{definitionRu:"Синтетическая тестовая сущность.",includedFormsRu:"Только тестовая форма.",excludedFormsRu:"Все реальные продукты.",processingBoundaryRu:"Исключительно fixture."},origin:{kind:"plant",scientificName:"Testus fixture"},intrinsicAllergenCodes:[],glutenCerealRelationship:"not_intrinsically_identified_as_gluten_cereal",dietaryPatternAssessments:T.GENERIC_PATTERNS.map(pattern=>({pattern,status:"compatible"})),sources:[source],reviews:[review("nutrition_food_definition_specialist","nutrition"),review("allergen_policy_specialist","allergen")]};
const entity={schemaVersion:T.GENERIC_ENTITY_SCHEMA_VERSION,foodId:"generic_food_ru_fixture_item",entityVersion:1,entityType:"generic_single_food",displayNameRu:"Тестовый продукт",primarySlotCode:"vegetables_fruit_berries",additionalSlotCodes:[],displayOrder:1,intrinsicProfileRef:{intrinsicProfileId:"generic_profile_ru_fixture_item",intrinsicProfileVersion:1},lifecycleStatus:"active",lifecycleReason:null,supersedes:null,supersededBy:null,contentHash:H};
const catalog=(changes={})=>({schemaVersion:T.GENERIC_CATALOG_SCHEMA_VERSION,marketVersion:"nutrimind.market.ru.v1",taxonomyVersion:"nutrimind.food-allergen.ru.v1",policyVersion:T.GENERIC_POLICY_VERSION,contentVersion:T.GENERIC_CONTENT_VERSION,coverageVersion:T.GENERIC_COVERAGE_VERSION,supportedEntityTypes:["generic_single_food"],supportedDietaryPatterns:[...T.GENERIC_PATTERNS],supportedSlotCodes:[...T.GENERIC_SLOTS],eligibleRestrictionContext:{foodAllergyStatus:"none",foodAllergenCodes:"must_be_empty",celiacStatus:"no"},entities:[entity],intrinsicProfiles:[profile],...changes});
const answers={selections:[1,0,0,3,1,0,0,1,1],userType:"general_user",ageGroup:"adult",goal:"maintenance",dailyActivity:"mostly_sitting",ageYears:30,sexForFormula:"female",heightCm:170,weightKg:65,informationalConsent:true};
const phase3a=runPhase3A(runQuestionnairePipeline(answers),normalizeCurrentMealPattern(1));
const context=(changes={})=>normalizeRestrictionContext({foodAllergyStatus:"none",celiacStatus:"no",dietaryPattern:"omnivore",...changes});

test("exact generic versions and strict catalog validate canonically and freeze",()=>{const input=catalog();const before=JSON.stringify(input);const result=validateGenericFoodCatalog(input,now);assert.equal(result.status,"valid",JSON.stringify(result.errorCodes));assert.equal(JSON.stringify(input),before);assert.ok(Object.isFrozen(result));assert.ok(Object.isFrozen(result.catalog.entities[0]));assert.equal(result.catalog.entities[0].entityType,"generic_single_food");assert.equal(Object.hasOwn(result.catalog,"supportedAllergenCodes"),false)});
test("empty is valid_empty while old, mixed, unknown and commercial fields fail closed",()=>{assert.equal(validateGenericFoodCatalog(catalog({entities:[],intrinsicProfiles:[]}),now).status,"valid_empty");for(const value of [catalog({schemaVersion:"nutrimind.food-catalog.schema.v1"}),catalog({coverageVersion:"nutrimind.catalog-coverage.ru.v1"}),{...catalog(),extra:true},catalog({intrinsicProfiles:[{...profile,crossContactStatus:"unknown"}]}),catalog({intrinsicProfiles:[{...profile,labelVerificationStatus:"not_applicable"}]})])assert.equal(validateGenericFoodCatalog(value,now).status,"invalid")});
test("positive intrinsic relationship is accepted but favorable matrix is structurally rejected",()=>{const positive=validateGenericFoodCatalog(catalog({intrinsicProfiles:[{...profile,intrinsicAllergenCodes:["eggs"]}]}),now);assert.equal(positive.status,"valid");assert.deepEqual(positive.catalog.intrinsicProfiles[0].intrinsicAllergenCodes,["eggs"]);assert.equal(validateGenericFoodCatalog(catalog({intrinsicProfiles:[{...profile,allergenAssessments:[]}]}),now).status,"invalid")});
test("review expiry is exact at 180 days and binding is mandatory",()=>{const reviewed="2026-01-01T00:00:00.000Z";const reviews=profile.reviews.map(r=>({...r,reviewedAt:reviewed}));assert.equal(validateGenericFoodCatalog(catalog({intrinsicProfiles:[{...profile,reviews}]}),"2026-06-29T23:59:59.999Z").status,"valid");assert.equal(validateGenericFoodCatalog(catalog({intrinsicProfiles:[{...profile,reviews}]}),"2026-06-30T00:00:00.000Z").status,"invalid");assert.equal(validateGenericFoodCatalog(catalog({intrinsicProfiles:[{...profile,reviews:profile.reviews.map((r,i)=>i?{...r,profileHash:S}:r)}]}),now).status,"invalid")});
test("capability is available only for calculated parent, allergy none, celiac no and nonempty catalog",()=>{const valid=validateGenericFoodCatalog(catalog(),now);const eligible=computeGenericExampleCapability({phase3AParent:phase3a,restrictionContext:context(),catalogValidation:valid});assert.equal(eligible.status,"generic_examples_available");assert.ok(Object.isFrozen(eligible));for(const c of [context({foodAllergyStatus:"known",foodAllergenCodes:["eggs"]}),context({foodAllergyStatus:"not_sure"}),context({celiacStatus:"confirmed"}),context({celiacStatus:"not_sure"}),context({dietaryPattern:"other"})])assert.equal(computeGenericExampleCapability({phase3AParent:phase3a,restrictionContext:c,catalogValidation:valid}).status,"generic_examples_unavailable");assert.equal(computeGenericExampleCapability({phase3AParent:null,restrictionContext:context(),catalogValidation:valid}).status,"generic_examples_unavailable");assert.equal(computeGenericExampleCapability({phase3AParent:phase3a,restrictionContext:context(),catalogValidation:validateGenericFoodCatalog(catalog({entities:[],intrinsicProfiles:[]}),now)}).status,"generic_examples_unavailable")});
test("filter uses only slot and exact pattern and never relaxes empty result",()=>{const valid=validateGenericFoodCatalog(catalog(),now),c=context(),cap=computeGenericExampleCapability({phase3AParent:phase3a,restrictionContext:c,catalogValidation:valid});const matched=filterGenericFoodCatalog(valid,cap,c,"vegetables_fruit_berries");assert.equal(matched.status,"matched");assert.deepEqual(matched.items.map(x=>x.foodId),["generic_food_ru_fixture_item"]);assert.ok(Object.isFrozen(matched));const empty=filterGenericFoodCatalog(valid,cap,c,"protein_source");assert.equal(empty.status,"empty");assert.deepEqual(empty.items,[]);assert.ok(empty.errorCodes.includes("GENERIC_FILTER_NO_MATCHES"));assert.equal(filterGenericFoodCatalog(valid,cap,c,"unknown").status,"slot_unsupported")});
test("pattern unknown excludes item and allergy context cannot reach filter",()=>{const v=validateGenericFoodCatalog(catalog({intrinsicProfiles:[{...profile,dietaryPatternAssessments:profile.dietaryPatternAssessments.map(x=>x.pattern==="vegan"?{...x,status:"unknown"}:x)}]}),now);const vegan=context({dietaryPattern:"vegan"}),cap=computeGenericExampleCapability({phase3AParent:phase3a,restrictionContext:vegan,catalogValidation:v});assert.equal(filterGenericFoodCatalog(v,cap,vegan,"vegetables_fruit_berries").status,"empty");const allergic=context({foodAllergyStatus:"known",foodAllergenCodes:["eggs"]});assert.equal(filterGenericFoodCatalog(v,cap,allergic,"vegetables_fruit_berries").status,"context_unavailable")});
test("generic modules contain no network persistence nutrition portions menus or cross-contact model",async()=>{const fs=await import("node:fs");const files=["types.ts","validator.ts","capability.ts","filter.ts"].map(x=>fs.readFileSync(new URL(`../core/generic-food-catalog/${x}`,import.meta.url),"utf8")).join("\n");assert.doesNotMatch(files,/fetch\(|localStorage|indexedDB|analytics/i);assert.doesNotMatch(JSON.stringify(catalog()),/crossContact|manufacturer|package|labelVerification|energyKcal|proteinG|fatG|carbohydrateG|portion|recipe|menu/i)});

test("old malformed missing and every non-none allergy context fail closed",()=>{const valid=validateGenericFoodCatalog(catalog(),now);const capability=c=>computeGenericExampleCapability({phase3AParent:phase3a,restrictionContext:c,catalogValidation:valid});assert.equal(capability(null).status,"generic_examples_unavailable");assert.equal(capability({...context(),schemaVersion:"nutrimind.phase3b2.restriction-context.v0"}).status,"generic_examples_unavailable");assert.equal(capability({...context(),status:"resolved",foodAllergyStatus:"malformed"}).status,"generic_examples_unavailable");for(const changes of [{foodAllergyStatus:"known",foodAllergenCodes:["eggs","milk"]},{foodAllergyStatus:"other"},{foodAllergyStatus:"not_sure"},{foodAllergyStatus:"prefer_not_to_say"}])assert.equal(capability(context(changes)).status,"generic_examples_unavailable")});

test("entity profile source and review schemas reject unknown commercial duplicate and broken binding data",()=>{const cases=[catalog({entities:[{...entity,extra:true}]}),catalog({intrinsicProfiles:[{...profile,manufacturer:"fixture"}]}),catalog({intrinsicProfiles:[{...profile,sources:[{...source,sourceType:"manufacturer_official_page"}]}]}),catalog({intrinsicProfiles:[{...profile,sources:[source,{...source}]}]}),catalog({intrinsicProfiles:[{...profile,reviews:[profile.reviews[0],{...profile.reviews[1],reviewerId:profile.reviews[0].reviewerId}]}]}),catalog({intrinsicProfiles:[{...profile,reviews:[review("technical_validator","one"),review("technical_validator","two")]}]}),catalog({entities:[{...entity,intrinsicProfileRef:{...entity.intrinsicProfileRef,intrinsicProfileId:"generic_profile_ru_fixture_missing"}}]})];for(const value of cases)assert.equal(validateGenericFoodCatalog(value,now).status,"invalid")});

test("duplicates and one malformed entry invalidate the whole catalog without quarantine",()=>{assert.equal(validateGenericFoodCatalog(catalog({entities:[entity,{...entity}],intrinsicProfiles:[profile,{...profile}]}),now).status,"invalid");const invalid=validateGenericFoodCatalog(catalog({entities:[entity,{...entity,foodId:"generic_food_ru_fixture_second",displayOrder:2}],intrinsicProfiles:[profile]}),now);assert.equal(invalid.status,"invalid");assert.equal(Object.hasOwn(invalid,"catalog"),false)});

test("catalog and profile arrays are canonicalized without mutating caller order",()=>{const p2={...structuredClone(profile),intrinsicProfileId:"generic_profile_ru_fixture_second",foodId:"generic_food_ru_fixture_second"};const e2={...structuredClone(entity),foodId:"generic_food_ru_fixture_second",displayNameRu:"Второй тестовый продукт",displayOrder:0,intrinsicProfileRef:{intrinsicProfileId:p2.intrinsicProfileId,intrinsicProfileVersion:1}};const input=catalog({entities:[entity,e2],intrinsicProfiles:[profile,p2]});const before=JSON.stringify(input);const result=validateGenericFoodCatalog(input,now);assert.equal(result.status,"valid",JSON.stringify(result.errorCodes));assert.deepEqual(result.catalog.entities.map(x=>x.foodId),[e2.foodId,entity.foodId]);assert.equal(JSON.stringify(input),before);assert.ok(Object.isFrozen(result.catalog.intrinsicProfiles[0].sources[0]))});

test("unsupported pattern malformed catalog withdrawn entity and forged capability never fail open",()=>{const valid=validateGenericFoodCatalog(catalog(),now);assert.equal(computeGenericExampleCapability({phase3AParent:phase3a,restrictionContext:context({dietaryPattern:"other"}),catalogValidation:valid}).status,"generic_examples_unavailable");assert.equal(computeGenericExampleCapability({phase3AParent:phase3a,restrictionContext:context(),catalogValidation:validateGenericFoodCatalog({broken:true},now)}).status,"generic_examples_unavailable");assert.equal(validateGenericFoodCatalog(catalog({entities:[{...entity,lifecycleStatus:"withdrawn",lifecycleReason:"emergency_withdrawal"}]}),now).status,"invalid");const forged={status:"generic_examples_available",warningCodes:[],errorCodes:[],ruleIds:[]};assert.equal(filterGenericFoodCatalog(valid,forged,{...context(),schemaVersion:"old"},"vegetables_fruit_berries").status,"context_unavailable")});

test("generic modules are not imported by production application and fixtures stay test-only",async()=>{const fs=await import("node:fs"),path=await import("node:path"),url=await import("node:url");const appRoot=url.fileURLToPath(new URL("../app/",import.meta.url));const walk=d=>fs.readdirSync(d,{withFileTypes:true}).flatMap(x=>x.isDirectory()?walk(path.join(d,x.name)):[path.join(d,x.name)]);const appSource=walk(appRoot).filter(x=>/\.[jt]sx?$/.test(x)).map(x=>fs.readFileSync(x,"utf8")).join("\n");assert.doesNotMatch(appSource,/generic-food-catalog|generic_single_food|generic_food_ru_fixture/);const production=fs.readdirSync(new URL("../core/generic-food-catalog/",import.meta.url)).map(x=>fs.readFileSync(new URL(`../core/generic-food-catalog/${x}`,import.meta.url),"utf8")).join("\n");assert.doesNotMatch(production,/generic_food_ru_fixture|example\.org|Тестовый продукт/)});
