import type { Phase3AResult } from "../calculation/types.ts";
import type { FoodAllergenCode, RestrictionContextV1 } from "../food-restrictions/types.ts";
import type { FoodGroupSlotId } from "../food-templates/types.ts";

export const GENERIC_CATALOG_SCHEMA_VERSION = "nutrimind.generic-food-catalog.schema.v1" as const;
export const GENERIC_ENTITY_SCHEMA_VERSION = "nutrimind.generic-food-catalog.entity.v1" as const;
export const GENERIC_PROFILE_SCHEMA_VERSION = "nutrimind.generic-food-catalog.intrinsic-profile.v1" as const;
export const GENERIC_SOURCE_SCHEMA_VERSION = "nutrimind.generic-food-catalog.source.v1" as const;
export const GENERIC_REVIEW_SCHEMA_VERSION = "nutrimind.generic-food-catalog.review.v1" as const;
export const GENERIC_POLICY_VERSION = "nutrimind.generic-food-catalog.policy.ru.v1" as const;
export const GENERIC_CONTENT_VERSION = "nutrimind.generic-food-catalog.ru.v1.0.0" as const;
export const GENERIC_COVERAGE_VERSION = "nutrimind.generic-food-catalog.coverage.ru.v1" as const;
export const GENERIC_PATTERNS = ["omnivore", "vegetarian", "vegan", "pescatarian"] as const;
export const GENERIC_SLOTS = ["protein_source", "carbohydrate_source", "vegetables_fruit_berries", "fat_source"] as const satisfies readonly FoodGroupSlotId[];
export const GENERIC_PATTERN_STATUSES = ["compatible", "not_compatible", "unknown", "not_assessed"] as const;
export const GENERIC_GLUTEN_RELATIONSHIPS = ["intrinsically_contains_gluten_cereal", "not_intrinsically_identified_as_gluten_cereal", "unknown"] as const;
export const GENERIC_SOURCE_TYPES = ["official_food_definition", "official_taxonomy", "official_clinical_guideline", "official_regulation", "recognized_food_reference"] as const;
export const GENERIC_SOURCE_PURPOSES = ["generic_identity", "botanical_animal_origin", "intrinsic_allergen_relationship", "gluten_cereal_relationship", "dietary_pattern_classification", "policy_context"] as const;
export const GENERIC_REVIEWER_ROLES = ["nutrition_food_definition_specialist", "allergen_policy_specialist", "technical_validator"] as const;
export const GENERIC_REVIEW_STATUSES = ["approved", "changes_required", "rejected"] as const;
export const GENERIC_LIFECYCLE_STATUSES = ["active", "deprecated", "withdrawn"] as const;
export const GENERIC_LIFECYCLE_REASONS = ["superseded", "source_changed", "policy_changed", "review_expired", "data_error", "safety_review_required", "emergency_withdrawal"] as const;

export const GENERIC_WARNING_CODES = ["GENERIC_EXAMPLES_NOT_ALLERGY_ASSESSED","GENERIC_EXAMPLES_NOT_CELIAC_ASSESSED","GENERIC_EXAMPLES_NO_CROSS_CONTACT_ASSESSMENT","GENERIC_CATALOG_LIMITED","GENERIC_EXAMPLES_DISABLED","GENERIC_CATALOG_EMPTY","GENERIC_CLIENT_SIDE_FILTERING_ONLY","GENERIC_PHASE3B1_FALLBACK","GENERIC_NO_PORTIONS","GENERIC_NO_MACRO_MATCHING","GENERIC_NO_MENUS","GENERIC_FILTER_ITEMS_EXCLUDED","GENERIC_FILTER_NO_MATCHES"] as const;
export const GENERIC_ERROR_CODES = ["GENERIC_CATALOG_MISSING","GENERIC_CATALOG_NOT_OBJECT","GENERIC_CATALOG_UNKNOWN_FIELD","GENERIC_CATALOG_SCHEMA_UNSUPPORTED","GENERIC_CATALOG_MARKET_UNSUPPORTED","GENERIC_CATALOG_TAXONOMY_UNSUPPORTED","GENERIC_CATALOG_POLICY_UNSUPPORTED","GENERIC_CATALOG_CONTENT_VERSION_UNSUPPORTED","GENERIC_CATALOG_COVERAGE_UNSUPPORTED","GENERIC_CATALOG_COVERAGE_INVALID","GENERIC_CATALOG_COLLECTION_INVALID","GENERIC_CATALOG_SIZE_EXCEEDED","GENERIC_CATALOG_DUPLICATE_ID","GENERIC_CATALOG_REFERENCE_INVALID","GENERIC_CATALOG_CONTAINS_INVALID_ENTRY","GENERIC_ENTITY_INVALID","GENERIC_PROFILE_INVALID","GENERIC_SOURCE_INVALID","GENERIC_REVIEW_INVALID","GENERIC_REVIEW_INDEPENDENCE_FAILED","GENERIC_REVIEW_REQUIRED_ROLE_MISSING","GENERIC_REVIEW_EXPIRED","GENERIC_REVIEW_BINDING_MISMATCH","GENERIC_CAPABILITY_PHASE3A_UNAVAILABLE","GENERIC_CAPABILITY_CONTEXT_UNAVAILABLE","GENERIC_CAPABILITY_ALLERGY_INELIGIBLE","GENERIC_CAPABILITY_ALLERGY_UNRESOLVED","GENERIC_CAPABILITY_CELIAC_CONFIRMED_INELIGIBLE","GENERIC_CAPABILITY_CELIAC_UNRESOLVED","GENERIC_CAPABILITY_DIETARY_PATTERN_UNSUPPORTED","GENERIC_CAPABILITY_CATALOG_UNAVAILABLE","GENERIC_CAPABILITY_CATALOG_INVALID","GENERIC_CAPABILITY_CATALOG_EMPTY","GENERIC_FILTER_CONTEXT_UNAVAILABLE","GENERIC_FILTER_CATALOG_UNAVAILABLE","GENERIC_FILTER_SLOT_UNSUPPORTED","GENERIC_FILTER_ENTITY_EXCLUDED_PATTERN","GENERIC_FILTER_ENTITY_EXCLUDED_LIFECYCLE","GENERIC_FILTER_NO_MATCHES"] as const;
export const GENERIC_RULE_IDS = ["GENERIC_FOOD_CATALOG.RU_MARKET_SCOPE.001","GENERIC_FOOD_CATALOG.EXPLICIT_ALLERGY_NONE_ONLY.001","GENERIC_FOOD_CATALOG.EXPLICIT_CELIAC_NO_ONLY.001","GENERIC_FOOD_CATALOG.NOT_ALLERGY_AWARE.001","GENERIC_FOOD_CATALOG.NOT_CELIAC_AWARE.001","GENERIC_FOOD_CATALOG.NO_CROSS_CONTACT_METADATA.001","GENERIC_FOOD_CATALOG.POSITIVE_INTRINSIC_ALLERGENS_ONLY.001","GENERIC_FOOD_CATALOG.EXPLICIT_PATTERN_COMPATIBILITY.001","GENERIC_FOOD_CATALOG.TWO_INDEPENDENT_SPECIALIST_REVIEWS.001","GENERIC_FOOD_CATALOG.REVIEW_EXPIRY_180_DAYS.001","GENERIC_FOOD_CATALOG.OLD_CONTEXT_FAIL_CLOSED.001","GENERIC_FOOD_CATALOG.MALFORMED_CATALOG_FAIL_CLOSED.001","GENERIC_FOOD_CATALOG.CLIENT_SIDE_FILTERING.001","GENERIC_FOOD_CATALOG.NO_PERSONALIZED_NETWORK.001","GENERIC_FOOD_CATALOG.PHASE3B1_FALLBACK.001","GENERIC_FOOD_CATALOG.NO_PORTIONS.001","GENERIC_FOOD_CATALOG.NO_MACRO_MATCHING.001","GENERIC_FOOD_CATALOG.NO_MENUS.001","GENERIC_FOOD_CATALOG.EMPTY_RESULT_NO_RELAXATION.001"] as const;

export type GenericPattern = typeof GENERIC_PATTERNS[number];
export type GenericWarningCode = typeof GENERIC_WARNING_CODES[number];
export type GenericErrorCode = typeof GENERIC_ERROR_CODES[number];
export type GenericRuleId = typeof GENERIC_RULE_IDS[number];
export type Sha256 = `sha256:${string}`;
export interface GenericPatternAssessmentV1 { pattern: GenericPattern; status: typeof GENERIC_PATTERN_STATUSES[number] }
export interface GenericCatalogSourceV1 { schemaVersion:typeof GENERIC_SOURCE_SCHEMA_VERSION;sourceId:string;sourceType:typeof GENERIC_SOURCE_TYPES[number];sourcePurpose:typeof GENERIC_SOURCE_PURPOSES[number];title:string;publisher:string;sourceVersion:string;publishedOn:string;verifiedOn:string;locatorType:"https_url"|"document_reference"|"asset_reference";locator:string;sourceFingerprint:Sha256 }
export interface GenericCatalogReviewV1 { schemaVersion:typeof GENERIC_REVIEW_SCHEMA_VERSION;reviewId:string;reviewerId:string;reviewerRole:typeof GENERIC_REVIEWER_ROLES[number];reviewStatus:typeof GENERIC_REVIEW_STATUSES[number];reviewedAt:string;profileHash:Sha256;sourceSetHash:Sha256;policyVersion:typeof GENERIC_POLICY_VERSION }
export interface GenericFoodEntityV1 { schemaVersion:typeof GENERIC_ENTITY_SCHEMA_VERSION;foodId:string;entityVersion:number;entityType:"generic_single_food";displayNameRu:string;primarySlotCode:FoodGroupSlotId;additionalSlotCodes:FoodGroupSlotId[];displayOrder:number;intrinsicProfileRef:{intrinsicProfileId:string;intrinsicProfileVersion:number};lifecycleStatus:typeof GENERIC_LIFECYCLE_STATUSES[number];lifecycleReason:typeof GENERIC_LIFECYCLE_REASONS[number]|null;supersedes:{foodId:string;entityVersion:number}|null;supersededBy:{foodId:string;entityVersion:number}|null;contentHash:Sha256 }
export interface GenericIntrinsicProfileV1 { schemaVersion:typeof GENERIC_PROFILE_SCHEMA_VERSION;intrinsicProfileId:string;intrinsicProfileVersion:number;foodId:string;entityVersion:number;profileHash:Sha256;sourceSetHash:Sha256;policyVersion:typeof GENERIC_POLICY_VERSION;genericIdentity:{definitionRu:string;includedFormsRu:string;excludedFormsRu:string;processingBoundaryRu:string};origin:{kind:"plant"|"animal";scientificName:string};intrinsicAllergenCodes:FoodAllergenCode[];glutenCerealRelationship:typeof GENERIC_GLUTEN_RELATIONSHIPS[number];dietaryPatternAssessments:GenericPatternAssessmentV1[];sources:GenericCatalogSourceV1[];reviews:GenericCatalogReviewV1[] }
export interface GenericFoodCatalogEnvelopeV1 { schemaVersion:typeof GENERIC_CATALOG_SCHEMA_VERSION;marketVersion:"nutrimind.market.ru.v1";taxonomyVersion:"nutrimind.food-allergen.ru.v1";policyVersion:typeof GENERIC_POLICY_VERSION;contentVersion:typeof GENERIC_CONTENT_VERSION;coverageVersion:typeof GENERIC_COVERAGE_VERSION;supportedEntityTypes:readonly ["generic_single_food"];supportedDietaryPatterns:GenericPattern[];supportedSlotCodes:FoodGroupSlotId[];eligibleRestrictionContext:{foodAllergyStatus:"none";foodAllergenCodes:"must_be_empty";celiacStatus:"no"};entities:GenericFoodEntityV1[];intrinsicProfiles:GenericIntrinsicProfileV1[] }
export type GenericCatalogValidationResult={status:"valid"|"valid_empty";catalog:GenericFoodCatalogEnvelopeV1;warningCodes:GenericWarningCode[];errorCodes:GenericErrorCode[];ruleIds:GenericRuleId[]}|{status:"invalid";warningCodes:GenericWarningCode[];errorCodes:GenericErrorCode[];ruleIds:GenericRuleId[]};
export interface GenericExampleCapabilityInputV1 { phase3AParent:Phase3AResult|null|undefined;restrictionContext:RestrictionContextV1|null|undefined;catalogValidation:GenericCatalogValidationResult|null|undefined }
export interface GenericExampleCapabilityResultV1 { status:"generic_examples_unavailable"|"generic_examples_available";warningCodes:GenericWarningCode[];errorCodes:GenericErrorCode[];ruleIds:GenericRuleId[] }
export interface GenericFilterResultV1 {status:"matched"|"empty"|"catalog_unavailable"|"context_unavailable"|"slot_unsupported";items:GenericFoodEntityV1[];exclusions:{foodId:string;errorCodes:GenericErrorCode[]}[];warningCodes:GenericWarningCode[];errorCodes:GenericErrorCode[];ruleIds:GenericRuleId[]}
