import type { FoodAllergenCode, RawDietaryPattern, RestrictionContextV1 } from "../food-restrictions/types.ts";
import type { FoodGroupSlotId } from "../food-templates/types.ts";

export const CATALOG_SCHEMA_VERSION="nutrimind.food-catalog.schema.v1" as const;
export const ENTITY_SCHEMA_VERSION="nutrimind.food-catalog.entity.v1" as const;
export const SAFETY_PROFILE_SCHEMA_VERSION="nutrimind.food-catalog.safety-profile.v1" as const;
export const SOURCE_SCHEMA_VERSION="nutrimind.food-catalog.source.v1" as const;
export const REVIEW_SCHEMA_VERSION="nutrimind.food-catalog.review.v1" as const;
export const CATALOG_POLICY_VERSION="nutrimind.food-catalog.policy.ru.v1" as const;
export const CATALOG_CONTENT_VERSION="nutrimind.food-catalog.ru.v1.0.0" as const;
export const FUTURE_COVERAGE_VERSION="nutrimind.catalog-coverage.ru.v1" as const;
export const FUTURE_SUPPORTED_ALLERGEN_CODES=["wheat","rye","barley","other_gluten_cereal","tree_nuts","peanuts","sesame","fish","crustaceans","molluscs","milk","eggs","soybeans","celery","mustard","lupin"] as const satisfies readonly FoodAllergenCode[];
export const SUPPORTED_PATTERNS=["omnivore","vegetarian","vegan","pescatarian"] as const;
export type SupportedDietaryPattern=typeof SUPPORTED_PATTERNS[number];
export const SLOT_CODES=["protein_source","carbohydrate_source","vegetables_fruit_berries","fat_source"] as const satisfies readonly FoodGroupSlotId[];
export const INGREDIENT_STATUSES=["contains","does_not_contain","unknown"] as const;
export const CROSS_CONTACT_STATUSES=["not_applicable","assessed_no_known_warning","may_contain","facility_warning","unknown","not_assessed"] as const;
export const CELIAC_STATUSES=["suitable","not_suitable","requires_verified_label","cross_contact_unknown","not_assessed","unsupported"] as const;
export const GLUTEN_RELATIONSHIPS=["contains_gluten_cereal","does_not_contain_gluten_cereal","unknown","not_assessed"] as const;
export const PATTERN_COMPATIBILITIES=["compatible","not_compatible","unknown","not_assessed"] as const;
export const LABEL_STATUSES=["not_applicable","required","verified","not_verified"] as const;
export const SOURCE_TYPES=["official_regulation","official_government_reference","official_clinical_guideline","manufacturer_official_specification","manufacturer_official_page","package_label_document","package_label_image"] as const;
export const LOCATOR_TYPES=["https_url","document_reference","asset_reference"] as const;
export const REVIEWER_ROLES=["allergen_celiac_specialist","nutrition_specialist","regulatory_labeling_specialist","technical_validator"] as const;
export const REVIEW_STATUSES=["approved","changes_required","rejected"] as const;
export const LIFECYCLE_STATUSES=["active","deprecated","withdrawn"] as const;
export const LIFECYCLE_REASONS=["superseded","source_changed","policy_changed","review_expired","data_error","safety_review_required","emergency_withdrawal"] as const;
export type IngredientPresenceStatus=typeof INGREDIENT_STATUSES[number]; export type CrossContactStatus=typeof CROSS_CONTACT_STATUSES[number];
export type CatalogCeliacStatus=typeof CELIAC_STATUSES[number]; export type GlutenRelationship=typeof GLUTEN_RELATIONSHIPS[number];
export type DietaryPatternCompatibility=typeof PATTERN_COMPATIBILITIES[number]; export type LabelVerificationStatus=typeof LABEL_STATUSES[number];
export type SourceType=typeof SOURCE_TYPES[number]; export type ReviewerRole=typeof REVIEWER_ROLES[number]; export type ReviewStatus=typeof REVIEW_STATUSES[number];
export type EntityLifecycleStatus=typeof LIFECYCLE_STATUSES[number]; export type EntityLifecycleReason=typeof LIFECYCLE_REASONS[number];
export type Sha256Code=`sha256:${string}`; export type FoodId=string; export type SafetyProfileId=string;
export interface EntityVersionRef { foodId:FoodId; entityVersion:number }
export interface AllergenAssessmentV1 { code:FoodAllergenCode; ingredientStatus:IngredientPresenceStatus; crossContactStatus:CrossContactStatus }
export interface DietaryPatternAssessmentV1 { pattern:SupportedDietaryPattern; status:DietaryPatternCompatibility }
export interface CatalogSourceV1 { schemaVersion:typeof SOURCE_SCHEMA_VERSION; sourceId:string; sourceType:SourceType; title:string; publisher:string; sourceVersion:string; publishedOn:string; verifiedOn:string; locatorType:typeof LOCATOR_TYPES[number]; locator:string; sourceFingerprint:Sha256Code }
export interface CatalogReviewV1 { schemaVersion:typeof REVIEW_SCHEMA_VERSION; reviewId:string; reviewerId:string; reviewerRole:ReviewerRole; reviewStatus:ReviewStatus; reviewedAt:string; profileHash:Sha256Code; sourceSetHash:Sha256Code; policyVersion:typeof CATALOG_POLICY_VERSION }
export interface FoodCatalogEntityV1 { schemaVersion:typeof ENTITY_SCHEMA_VERSION; foodId:FoodId; entityVersion:number; entityType:"single_food"; displayNameRu:string; slotCodes:readonly FoodGroupSlotId[]; displayOrder:number; safetyProfileRef:{safetyProfileId:SafetyProfileId;safetyProfileVersion:number}; lifecycleStatus:EntityLifecycleStatus; lifecycleReason:EntityLifecycleReason|null; supersedes:EntityVersionRef|null; supersededBy:EntityVersionRef|null; contentHash:Sha256Code }
export interface FoodSafetyProfileV1 { schemaVersion:typeof SAFETY_PROFILE_SCHEMA_VERSION; safetyProfileId:SafetyProfileId; safetyProfileVersion:number; foodId:FoodId; entityVersion:number; profileHash:Sha256Code; sourceSetHash:Sha256Code; policyVersion:typeof CATALOG_POLICY_VERSION; allergenAssessments:readonly AllergenAssessmentV1[]; glutenRelationship:GlutenRelationship; celiacStatus:CatalogCeliacStatus; dietaryPatternAssessments:readonly DietaryPatternAssessmentV1[]; labelVerificationStatus:LabelVerificationStatus; sources:readonly CatalogSourceV1[]; reviews:readonly CatalogReviewV1[] }
export interface FoodCatalogEnvelopeV1 { schemaVersion:typeof CATALOG_SCHEMA_VERSION; marketVersion:"nutrimind.market.ru.v1"; taxonomyVersion:"nutrimind.food-allergen.ru.v1"; policyVersion:typeof CATALOG_POLICY_VERSION; contentVersion:typeof CATALOG_CONTENT_VERSION; coverageVersion:typeof FUTURE_COVERAGE_VERSION; supportedEntityTypes:readonly ["single_food"]; catalogSupportedAllergenCodes:readonly FoodAllergenCode[]; catalogSupportedDietaryPatterns:readonly SupportedDietaryPattern[]; catalogCeliacSupport:"not_supported"; entities:readonly FoodCatalogEntityV1[]; safetyProfiles:readonly FoodSafetyProfileV1[] }

export const CATALOG_WARNING_CODES=["CATALOG_NO_PRODUCTION_CONTENT","CATALOG_EMPTY","CATALOG_COVERAGE_NOT_ACTIVE","CATALOG_CONCRETE_OUTPUT_DISABLED","CATALOG_CELIAC_NOT_SUPPORTED","CATALOG_OATS_NOT_SUPPORTED","CATALOG_CROSS_CONTACT_FAIL_CLOSED","CATALOG_REVIEW_EXPIRY_180_DAYS","CATALOG_CLIENT_SIDE_FILTERING_ONLY","CATALOG_PHASE3B1_FALLBACK","CATALOG_NO_PORTIONS","CATALOG_NO_MACRO_MATCHING","FILTER_ITEMS_EXCLUDED","FILTER_NO_MATCHES"] as const;
export type CatalogWarningCode=typeof CATALOG_WARNING_CODES[number];
export const CATALOG_ERROR_CODES=["CATALOG_MISSING","CATALOG_NOT_OBJECT","CATALOG_UNKNOWN_FIELD","CATALOG_SCHEMA_UNSUPPORTED","CATALOG_MARKET_UNSUPPORTED","CATALOG_TAXONOMY_UNSUPPORTED","CATALOG_POLICY_UNSUPPORTED","CATALOG_CONTENT_VERSION_UNSUPPORTED","CATALOG_COVERAGE_UNSUPPORTED","CATALOG_COVERAGE_INVALID","CATALOG_COLLECTION_INVALID","CATALOG_SIZE_EXCEEDED","CATALOG_DUPLICATE_ID","CATALOG_REFERENCE_INVALID","CATALOG_CONTAINS_INVALID_ENTRY","ENTITY_NOT_OBJECT","ENTITY_UNKNOWN_FIELD","ENTITY_SCHEMA_UNSUPPORTED","ENTITY_ID_INVALID","ENTITY_VERSION_INVALID","ENTITY_TYPE_UNSUPPORTED","ENTITY_LABEL_INVALID","ENTITY_SLOT_INVALID","ENTITY_ORDER_INVALID","ENTITY_PROFILE_REF_INVALID","ENTITY_HASH_INVALID","ENTITY_LIFECYCLE_INVALID","ENTITY_SUPERSESSION_INVALID","PROFILE_NOT_OBJECT","PROFILE_UNKNOWN_FIELD","PROFILE_SCHEMA_UNSUPPORTED","PROFILE_ID_INVALID","PROFILE_VERSION_INVALID","PROFILE_ENTITY_MISMATCH","PROFILE_HASH_INVALID","PROFILE_POLICY_UNSUPPORTED","PROFILE_ALLERGEN_MATRIX_INVALID","PROFILE_GLUTEN_RELATIONSHIP_INVALID","PROFILE_CELIAC_STATUS_INVALID","PROFILE_PATTERN_MATRIX_INVALID","PROFILE_PATTERN_CONFLICT","PROFILE_LABEL_VERIFICATION_INVALID","SOURCE_COLLECTION_INVALID","SOURCE_RECORD_INVALID","SOURCE_UNKNOWN_FIELD","SOURCE_TYPE_UNSUPPORTED","SOURCE_DATE_INVALID","SOURCE_LOCATOR_INVALID","SOURCE_HASH_INVALID","SOURCE_DUPLICATE","SOURCE_SET_HASH_MISMATCH","REVIEW_COLLECTION_INVALID","REVIEW_RECORD_INVALID","REVIEW_UNKNOWN_FIELD","REVIEW_ROLE_UNSUPPORTED","REVIEW_STATUS_INVALID","REVIEW_DUPLICATE","REVIEW_INDEPENDENCE_FAILED","REVIEW_REQUIRED_ROLE_MISSING","REVIEW_EXPIRED","REVIEW_BINDING_MISMATCH","CAPABILITY_CONTEXT_UNAVAILABLE","CAPABILITY_CATALOG_UNAVAILABLE","CAPABILITY_COVERAGE_UNSUPPORTED","CAPABILITY_CELIAC_UNSUPPORTED","CAPABILITY_OATS_UNSUPPORTED","FILTER_REQUEST_INVALID","FILTER_SLOT_UNSUPPORTED","FILTER_ENTITY_EXCLUDED_ALLERGEN","FILTER_ENTITY_EXCLUDED_CROSS_CONTACT","FILTER_ENTITY_EXCLUDED_PATTERN","FILTER_NO_MATCHES"] as const;
export type CatalogErrorCode=typeof CATALOG_ERROR_CODES[number];
export const CATALOG_RULE_IDS=["FOOD_CATALOG.RU_MARKET_SCOPE.001","FOOD_CATALOG.NO_PRODUCTION_CONTENT.001","FOOD_CATALOG.ENTITY_PROFILE_SEPARATION.001","FOOD_CATALOG.SINGLE_FOOD_ONLY_V1.001","FOOD_CATALOG.FULL_ALLERGEN_MATRIX.001","FOOD_CATALOG.EXACT_RESTRICTION_INTERSECTION.001","FOOD_CATALOG.UNKNOWN_METADATA_FAIL_CLOSED.001","FOOD_CATALOG.CROSS_CONTACT_SEPARATE.001","FOOD_CATALOG.CELIAC_SEPARATE_GATE.001","FOOD_CATALOG.CELIAC_NOT_SUPPORTED_V1.001","FOOD_CATALOG.OATS_NOT_SUPPORTED_V1.001","FOOD_CATALOG.DIETARY_PATTERN_EXPLICIT.001","FOOD_CATALOG.SOURCE_REQUIRED.001","FOOD_CATALOG.TWO_SPECIALIST_REVIEWS.001","FOOD_CATALOG.REVIEW_EXPIRY_180_DAYS.001","FOOD_CATALOG.REVIEW_BINDING_REQUIRED.001","FOOD_CATALOG.DEPRECATED_EXCLUDED.001","FOOD_CATALOG.WITHDRAWN_EXCLUDED.001","FOOD_CATALOG.MALFORMED_CATALOG_DISABLES_CONCRETE.001","FOOD_CATALOG.CLIENT_SIDE_FILTERING.001","FOOD_CATALOG.NO_PERSONALIZED_NETWORK.001","FOOD_CATALOG.PHASE3B1_FALLBACK.001","FOOD_CATALOG.NO_PORTIONS.001","FOOD_CATALOG.NO_MACRO_MATCHING.001","FOOD_CATALOG.EMPTY_RESULT_NO_RESTRICTION_RELAXATION.001"] as const;
export type CatalogRuleId=typeof CATALOG_RULE_IDS[number];
export type CatalogValidationResult={status:"valid"|"valid_empty";catalog:FoodCatalogEnvelopeV1;warningCodes:readonly CatalogWarningCode[];errorCodes:readonly CatalogErrorCode[];ruleIds:readonly CatalogRuleId[]}|{status:"invalid";warningCodes:readonly CatalogWarningCode[];errorCodes:readonly CatalogErrorCode[];ruleIds:readonly CatalogRuleId[]};
export interface CatalogCapabilityResult {status:"abstract_only"|"concrete_available";warningCodes:readonly CatalogWarningCode[];errorCodes:readonly CatalogErrorCode[];ruleIds:readonly CatalogRuleId[]}
export interface CatalogFilterResult {status:"matched"|"empty"|"catalog_unavailable"|"context_unavailable"|"slot_unsupported";items:readonly FoodCatalogEntityV1[];exclusions:readonly {foodId:FoodId;errorCodes:readonly CatalogErrorCode[]}[];warningCodes:readonly CatalogWarningCode[];errorCodes:readonly CatalogErrorCode[];ruleIds:readonly CatalogRuleId[]}
export type CatalogRestrictionContext=RestrictionContextV1;
