import { ALLERGEN_CODES } from "../food-restrictions/taxonomy.ts";
import { ALLERGEN_TAXONOMY_VERSION, MARKET_VERSION } from "../food-restrictions/types.ts";
import * as T from "./types.ts";

const plain=(v:unknown):v is Record<string,unknown>=>typeof v==="object"&&v!==null&&!Array.isArray(v)&&Object.getPrototypeOf(v)===Object.prototype;
const exact=(o:Record<string,unknown>,keys:readonly string[])=>Object.keys(o).length===keys.length&&keys.every(k=>k in o);
const member=<X extends string>(a:readonly X[],v:unknown):v is X=>typeof v==="string"&&a.includes(v as X);
const ver=(v:unknown)=>Number.isInteger(v)&&Number(v)>=1&&Number(v)<=2147483647;
const hash=(v:unknown)=>typeof v==="string"&&/^sha256:[0-9a-f]{64}$/.test(v);
const id=(v:unknown,re:RegExp,min:number,max:number)=>typeof v==="string"&&v.length>=min&&v.length<=max&&re.test(v);
const text=(v:unknown,min:number,max:number)=>typeof v==="string"&&v===v.trim()&&v===v.normalize("NFC")&&[...v].length>=min&&[...v].length<=max&&!/[\u0000-\u001f\u007f-\u009f<>]|[\uD800-\uDFFF]/u.test(v);
const isoDate=(v:unknown)=>typeof v==="string"&&/^\d{4}-\d{2}-\d{2}$/.test(v)&&!Number.isNaN(Date.parse(v+"T00:00:00.000Z"));
const isoTime=(v:unknown)=>typeof v==="string"&&/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/.test(v)&&!Number.isNaN(Date.parse(v));
export const deepFreeze=<X>(v:X):X=>{if(v&&typeof v==="object"&&!Object.isFrozen(v)){for(const x of Object.values(v as Record<string,unknown>))deepFreeze(x);Object.freeze(v)}return v};
const clone=<X>(v:X):X=>structuredClone(v);
const canon=<X extends string>(values:readonly X[],order:readonly X[])=>[...new Set(values)].sort((a,b)=>order.indexOf(a)-order.indexOf(b));
const errors=(values:T.CatalogErrorCode[])=>canon(values,T.CATALOG_ERROR_CODES);
const warnings=(values:T.CatalogWarningCode[])=>canon(values,T.CATALOG_WARNING_CODES);
const bad=(es:T.CatalogErrorCode[]):T.CatalogValidationResult=>deepFreeze({status:"invalid",warningCodes:warnings(["CATALOG_CONCRETE_OUTPUT_DISABLED","CATALOG_PHASE3B1_FALLBACK"]),errorCodes:errors(es),ruleIds:[...T.CATALOG_RULE_IDS]});

export function validateEntity(raw:unknown):{status:"valid";value:T.FoodCatalogEntityV1}|{status:"invalid";errorCodes:readonly T.CatalogErrorCode[]}{
 const e:T.CatalogErrorCode[]=[]; if(!plain(raw))return {status:"invalid",errorCodes:["ENTITY_NOT_OBJECT"]};
 const keys=["schemaVersion","foodId","entityVersion","entityType","displayNameRu","slotCodes","displayOrder","safetyProfileRef","lifecycleStatus","lifecycleReason","supersedes","supersededBy","contentHash"];
 if(!exact(raw,keys))e.push("ENTITY_UNKNOWN_FIELD"); if(raw.schemaVersion!==T.ENTITY_SCHEMA_VERSION)e.push("ENTITY_SCHEMA_UNSUPPORTED");
 if(!id(raw.foodId,/^food_ru_[a-z0-9]+(?:_[a-z0-9]+)*$/,9,80))e.push("ENTITY_ID_INVALID"); if(!ver(raw.entityVersion))e.push("ENTITY_VERSION_INVALID"); if(raw.entityType!=="single_food")e.push("ENTITY_TYPE_UNSUPPORTED"); if(!text(raw.displayNameRu,1,120))e.push("ENTITY_LABEL_INVALID");
 if(!Array.isArray(raw.slotCodes)||raw.slotCodes.length<1||raw.slotCodes.length>4||new Set(raw.slotCodes).size!==raw.slotCodes.length||!raw.slotCodes.every(x=>member(T.SLOT_CODES,x)))e.push("ENTITY_SLOT_INVALID"); if(!Number.isInteger(raw.displayOrder)||Number(raw.displayOrder)<0)e.push("ENTITY_ORDER_INVALID");
 if(!plain(raw.safetyProfileRef)||!exact(raw.safetyProfileRef,["safetyProfileId","safetyProfileVersion"])||!id(raw.safetyProfileRef.safetyProfileId,/^profile_ru_[a-z0-9]+(?:_[a-z0-9]+)*$/,12,96)||!ver(raw.safetyProfileRef.safetyProfileVersion))e.push("ENTITY_PROFILE_REF_INVALID");
 if(!hash(raw.contentHash))e.push("ENTITY_HASH_INVALID"); if(raw.lifecycleStatus!=="active"||raw.lifecycleReason!==null||raw.supersededBy!==null)e.push("ENTITY_LIFECYCLE_INVALID");
 for(const [k,dir] of [["supersedes",-1],["supersededBy",1]] as const){const x=raw[k];if(x!==null&&(!plain(x)||!exact(x,["foodId","entityVersion"])||x.foodId!==raw.foodId||!ver(x.entityVersion)||(dir<0&&Number(x.entityVersion)>=Number(raw.entityVersion))||(dir>0&&Number(x.entityVersion)<=Number(raw.entityVersion))))e.push("ENTITY_SUPERSESSION_INVALID")}
 return e.length?{status:"invalid",errorCodes:errors(e)}:{status:"valid",value:deepFreeze(clone(raw) as unknown as T.FoodCatalogEntityV1)};
}

function validateProfile(raw:unknown,asOfMs:number):{status:"valid";value:T.FoodSafetyProfileV1}|{status:"invalid";errorCodes:readonly T.CatalogErrorCode[]}{
 const e:T.CatalogErrorCode[]=[];if(!plain(raw))return{status:"invalid",errorCodes:["PROFILE_NOT_OBJECT"]};const keys=["schemaVersion","safetyProfileId","safetyProfileVersion","foodId","entityVersion","profileHash","sourceSetHash","policyVersion","allergenAssessments","glutenRelationship","celiacStatus","dietaryPatternAssessments","labelVerificationStatus","sources","reviews"];
 if(!exact(raw,keys))e.push("PROFILE_UNKNOWN_FIELD");if(raw.schemaVersion!==T.SAFETY_PROFILE_SCHEMA_VERSION)e.push("PROFILE_SCHEMA_UNSUPPORTED");if(!id(raw.safetyProfileId,/^profile_ru_[a-z0-9]+(?:_[a-z0-9]+)*$/,12,96))e.push("PROFILE_ID_INVALID");if(!ver(raw.safetyProfileVersion))e.push("PROFILE_VERSION_INVALID");if(!id(raw.foodId,/^food_ru_[a-z0-9]+(?:_[a-z0-9]+)*$/,9,80)||!ver(raw.entityVersion))e.push("PROFILE_ENTITY_MISMATCH");if(!hash(raw.profileHash)||!hash(raw.sourceSetHash))e.push("PROFILE_HASH_INVALID");if(raw.policyVersion!==T.CATALOG_POLICY_VERSION)e.push("PROFILE_POLICY_UNSUPPORTED");
 if(!Array.isArray(raw.allergenAssessments)||raw.allergenAssessments.length!==ALLERGEN_CODES.length||new Set(raw.allergenAssessments.map(a=>plain(a)?a.code:null)).size!==ALLERGEN_CODES.length||raw.allergenAssessments.some(a=>!plain(a)||!exact(a,["code","ingredientStatus","crossContactStatus"])||!member(ALLERGEN_CODES,a.code)||!member(T.INGREDIENT_STATUSES,a.ingredientStatus)||!member(T.CROSS_CONTACT_STATUSES,a.crossContactStatus)))e.push("PROFILE_ALLERGEN_MATRIX_INVALID");
 if(!member(T.GLUTEN_RELATIONSHIPS,raw.glutenRelationship))e.push("PROFILE_GLUTEN_RELATIONSHIP_INVALID");if(!member(T.CELIAC_STATUSES,raw.celiacStatus))e.push("PROFILE_CELIAC_STATUS_INVALID");
 if(!Array.isArray(raw.dietaryPatternAssessments)||raw.dietaryPatternAssessments.length!==4||new Set(raw.dietaryPatternAssessments.map(a=>plain(a)?a.pattern:null)).size!==4||raw.dietaryPatternAssessments.some(a=>!plain(a)||!exact(a,["pattern","status"])||!member(T.SUPPORTED_PATTERNS,a.pattern)||!member(T.PATTERN_COMPATIBILITIES,a.status)))e.push("PROFILE_PATTERN_MATRIX_INVALID");else{const m=Object.fromEntries(raw.dietaryPatternAssessments.map(a=>[a.pattern,a.status]));if(m.omnivore!=="compatible"||(m.pescatarian==="compatible"&&m.omnivore!=="compatible")||(m.vegetarian==="compatible"&&(m.pescatarian!=="compatible"||m.omnivore!=="compatible"))||(m.vegan==="compatible"&&(m.vegetarian!=="compatible"||m.pescatarian!=="compatible"||m.omnivore!=="compatible")))e.push("PROFILE_PATTERN_CONFLICT")}
 if(raw.labelVerificationStatus!=="not_applicable")e.push("PROFILE_LABEL_VERIFICATION_INVALID");
 if(!Array.isArray(raw.sources)||raw.sources.length<1||raw.sources.length>8)e.push("SOURCE_COLLECTION_INVALID");else{const ids=new Set;for(const s of raw.sources){if(!plain(s)||!exact(s,["schemaVersion","sourceId","sourceType","title","publisher","sourceVersion","publishedOn","verifiedOn","locatorType","locator","sourceFingerprint"]))e.push("SOURCE_RECORD_INVALID");else{if(s.schemaVersion!==T.SOURCE_SCHEMA_VERSION)e.push("SOURCE_RECORD_INVALID");if(!id(s.sourceId,/^source_[a-z0-9]+(?:_[a-z0-9]+)*$/,8,96)){e.push("SOURCE_RECORD_INVALID")}else if(ids.has(s.sourceId))e.push("SOURCE_DUPLICATE");else ids.add(s.sourceId);if(!member(T.SOURCE_TYPES,s.sourceType))e.push("SOURCE_TYPE_UNSUPPORTED");if(!text(s.title,1,160)||!text(s.publisher,1,120)||!text(s.sourceVersion,1,80))e.push("SOURCE_RECORD_INVALID");if(!isoDate(s.publishedOn)||!isoDate(s.verifiedOn)||Date.parse(String(s.verifiedOn)+"T00:00:00.000Z")<Date.parse(String(s.publishedOn)+"T00:00:00.000Z")||Date.parse(String(s.verifiedOn)+"T00:00:00.000Z")>asOfMs)e.push("SOURCE_DATE_INVALID");if(!member(T.LOCATOR_TYPES,s.locatorType)||typeof s.locator!=="string"||/[\u0000-\u001f\u007f-\u009f]/.test(s.locator)||(s.locatorType==="https_url"&&(()=>{try{const u=new URL(s.locator);return u.protocol!=="https:"||!!u.username||!!u.password||s.locator.length>2048}catch{return true}})())||(s.locatorType!=="https_url"&&s.locator.length>512))e.push("SOURCE_LOCATOR_INVALID");if(!hash(s.sourceFingerprint))e.push("SOURCE_HASH_INVALID")}}}
 if(!Array.isArray(raw.reviews)||raw.reviews.length<2||raw.reviews.length>4)e.push("REVIEW_COLLECTION_INVALID");else{const ids=new Set,reviewers=new Set;let allergy=false,other=false;for(const r of raw.reviews){if(!plain(r)||!exact(r,["schemaVersion","reviewId","reviewerId","reviewerRole","reviewStatus","reviewedAt","profileHash","sourceSetHash","policyVersion"]))e.push("REVIEW_RECORD_INVALID");else{if(r.schemaVersion!==T.REVIEW_SCHEMA_VERSION||!id(r.reviewId,/^review_[a-z0-9]+(?:_[a-z0-9]+)*$/,8,96)||!id(r.reviewerId,/^reviewer_[a-z0-9]+(?:_[a-z0-9]+)*$/,10,96))e.push("REVIEW_RECORD_INVALID");if(ids.has(r.reviewId)||reviewers.has(r.reviewerId))e.push("REVIEW_DUPLICATE");ids.add(r.reviewId);reviewers.add(r.reviewerId);if(!member(T.REVIEWER_ROLES,r.reviewerRole))e.push("REVIEW_ROLE_UNSUPPORTED");if(!member(T.REVIEW_STATUSES,r.reviewStatus))e.push("REVIEW_STATUS_INVALID");if(r.profileHash!==raw.profileHash||r.sourceSetHash!==raw.sourceSetHash||r.policyVersion!==T.CATALOG_POLICY_VERSION)e.push("REVIEW_BINDING_MISMATCH");if(!isoTime(r.reviewedAt)||Date.parse(String(r.reviewedAt))>asOfMs)e.push("REVIEW_RECORD_INVALID");else if(r.reviewStatus==="approved"&&asOfMs>=Date.parse(String(r.reviewedAt))+180*86400000)e.push("REVIEW_EXPIRED");if(r.reviewStatus==="approved"&&r.reviewerRole==="allergen_celiac_specialist")allergy=true;if(r.reviewStatus==="approved"&&(r.reviewerRole==="nutrition_specialist"||r.reviewerRole==="regulatory_labeling_specialist"))other=true}}if(!allergy||!other)e.push("REVIEW_REQUIRED_ROLE_MISSING")}
 if(e.length)return{status:"invalid",errorCodes:errors(e)};
 const value=clone(raw) as unknown as T.FoodSafetyProfileV1;
 value.allergenAssessments=[...value.allergenAssessments].sort((a,b)=>ALLERGEN_CODES.indexOf(a.code)-ALLERGEN_CODES.indexOf(b.code));
 value.dietaryPatternAssessments=[...value.dietaryPatternAssessments].sort((a,b)=>T.SUPPORTED_PATTERNS.indexOf(a.pattern)-T.SUPPORTED_PATTERNS.indexOf(b.pattern));
 value.sources=[...value.sources].sort((a,b)=>T.SOURCE_TYPES.indexOf(a.sourceType)-T.SOURCE_TYPES.indexOf(b.sourceType)||a.sourceId.localeCompare(b.sourceId));
 value.reviews=[...value.reviews].sort((a,b)=>T.REVIEWER_ROLES.indexOf(a.reviewerRole)-T.REVIEWER_ROLES.indexOf(b.reviewerRole)||a.reviewerId.localeCompare(b.reviewerId)||a.reviewedAt.localeCompare(b.reviewedAt));
 return{status:"valid",value:deepFreeze(value)};
}

export function validateFoodCatalog(raw:unknown,asOf:string):T.CatalogValidationResult{
 if(raw===null||raw===undefined)return bad(["CATALOG_MISSING"]);if(!plain(raw))return bad(["CATALOG_NOT_OBJECT"]);if(!isoTime(asOf))return bad(["CATALOG_CONTAINS_INVALID_ENTRY"]);const e:T.CatalogErrorCode[]=[];const keys=["schemaVersion","marketVersion","taxonomyVersion","policyVersion","contentVersion","coverageVersion","supportedEntityTypes","catalogSupportedAllergenCodes","catalogSupportedDietaryPatterns","catalogCeliacSupport","entities","safetyProfiles"];
 if(!exact(raw,keys))e.push("CATALOG_UNKNOWN_FIELD");if(raw.schemaVersion!==T.CATALOG_SCHEMA_VERSION)e.push("CATALOG_SCHEMA_UNSUPPORTED");if(raw.marketVersion!==MARKET_VERSION)e.push("CATALOG_MARKET_UNSUPPORTED");if(raw.taxonomyVersion!==ALLERGEN_TAXONOMY_VERSION)e.push("CATALOG_TAXONOMY_UNSUPPORTED");if(raw.policyVersion!==T.CATALOG_POLICY_VERSION)e.push("CATALOG_POLICY_UNSUPPORTED");if(raw.contentVersion!==T.CATALOG_CONTENT_VERSION)e.push("CATALOG_CONTENT_VERSION_UNSUPPORTED");if(raw.coverageVersion!==T.FUTURE_COVERAGE_VERSION)e.push("CATALOG_COVERAGE_UNSUPPORTED");
 if(!Array.isArray(raw.supportedEntityTypes)||raw.supportedEntityTypes.length!==1||raw.supportedEntityTypes[0]!=="single_food"||!Array.isArray(raw.catalogSupportedAllergenCodes)||JSON.stringify(raw.catalogSupportedAllergenCodes)!==JSON.stringify(T.FUTURE_SUPPORTED_ALLERGEN_CODES)||!Array.isArray(raw.catalogSupportedDietaryPatterns)||JSON.stringify(raw.catalogSupportedDietaryPatterns)!==JSON.stringify(T.SUPPORTED_PATTERNS)||raw.catalogCeliacSupport!=="not_supported")e.push("CATALOG_COVERAGE_INVALID");
 if(!Array.isArray(raw.entities)||!Array.isArray(raw.safetyProfiles))e.push("CATALOG_COLLECTION_INVALID");else if(raw.entities.length>250||raw.safetyProfiles.length>250)e.push("CATALOG_SIZE_EXCEEDED");if(e.length)return bad(e);const es=[] as T.FoodCatalogEntityV1[],ps=[] as T.FoodSafetyProfileV1[],allE:T.CatalogErrorCode[]=[];for(const x of raw.entities as unknown[]){const r=validateEntity(x);if(r.status==="valid")es.push(r.value);else allE.push(...r.errorCodes)}for(const x of raw.safetyProfiles as unknown[]){const r=validateProfile(x,Date.parse(asOf));if(r.status==="valid")ps.push(r.value);else allE.push(...r.errorCodes)}
 if(es.length!==ps.length)allE.push("CATALOG_REFERENCE_INVALID");if(new Set(es.map(x=>x.foodId)).size!==es.length||new Set(ps.map(x=>x.safetyProfileId)).size!==ps.length)allE.push("CATALOG_DUPLICATE_ID");for(const x of es){const p=ps.find(y=>y.safetyProfileId===x.safetyProfileRef.safetyProfileId);if(!p||p.safetyProfileVersion!==x.safetyProfileRef.safetyProfileVersion||p.foodId!==x.foodId||p.entityVersion!==x.entityVersion)allE.push("CATALOG_REFERENCE_INVALID")}for(const p of ps)if(!es.some(x=>x.foodId===p.foodId&&x.entityVersion===p.entityVersion&&x.safetyProfileRef.safetyProfileId===p.safetyProfileId))allE.push("CATALOG_REFERENCE_INVALID");if(allE.length)return bad(["CATALOG_CONTAINS_INVALID_ENTRY",...allE]);
 const catalog=clone(raw) as unknown as T.FoodCatalogEnvelopeV1;catalog.entities=[...es].sort((a,b)=>a.displayOrder-b.displayOrder||a.foodId.localeCompare(b.foodId));catalog.safetyProfiles=[...ps].sort((a,b)=>a.safetyProfileId.localeCompare(b.safetyProfileId)||a.safetyProfileVersion-b.safetyProfileVersion);return deepFreeze({status:es.length?"valid":"valid_empty",catalog:deepFreeze(catalog),warningCodes:warnings(es.length?[]:["CATALOG_EMPTY"]),errorCodes:[],ruleIds:[...T.CATALOG_RULE_IDS]});
}
